ATM/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls.conf import include

urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('atm/', include('atm_functions.urls', namespace='atm_functions')),
    path('businesses/', include('businesses.urls', namespace='businesses')),
    path('webhooks/', include('webhooks.urls', namespace='webhooks')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('cryptosharepay/', include('cryptosharepay.urls', namespace='cryptosharepay')),
    # path('admin/', admin.site.urls),
]

atm_functions/urls.py
from django.urls import path
from . import views

app_name = "atm_functions"
urlpatterns = [
     path("", views.home, name="Home"),
     path("ApproveWallet/", views.approve_wallet, name="ApproveWallet"),

     path("Contacts/", views.contacts, name="Contacts"),
     path("Contacts/Create", views.create_contact, name="CreateContact"),
     path("Contacts/Delete", views.delete_contact, name="DeleteContact"),

     path("Referrals/", views.referrals, name="Referrals"),
     path("ReferralsAdmin/", views.referrals_admin, name="ReferralsAdmin"),

     # path("EstateNetWorth/", views.estate_net_worth, name="EstateNetWorth"),
     # path("EditEstateNetWorth/", views.edit_estate_net_worth, name="EditEstateNetWorth"),

     # path("BlockchainWills/", views.blockchain_wills, name="BlockchainWills"),
     # path("RegisterBlockchainWill/", views.register_blockchain_will, name="RegisterBlockchainWill"),
     # path("CertificateBlockchainWill/", views.certificate_blockchain_will, name="CertificateBlockchainWill"),     
     # path("CertificateBlockchainWill/<int:id>/", views.certificate_blockchain_will, name="CertificateBlockchainWill"),    

     path("BuyCrypto/", views.buy_crypto, name="BuyCrypto"),
     path("BuildCredit/", views.buy_credit, name="BuildCredit"),
     path("BuyCryptoWidget/", views.buy_crypto_widget, name="BuyCryptoWidget"),

     path("BuildCreditCrypto/<str:code>/", views.buy_credit_with_crypto, name="BuildCreditCrypto"),

     path("CheckCredit/", views.check_balance, name="CheckCredit"),
     path("CreditGrades/", views.credit_grades, name="CreditGrades"),
     path("CryptoShareWallet/", views.cryptoshare_wallet, name="CryptoShareWallet"),

     path("CreditRatings/", views.credit_rankings, name="CreditRatings"),

     path("StripeCheckout/", views.stripe_checkout, name="StripeCheckout"),
     path("StripeCheckoutResult/", views.stripe_checkout_result, name="StripeCheckoutResult"),

     path("CryptoNews/", views.crypto_news, name="CryptoNews"),

     path("ConnectWallet/", views.connect_wallet, name="ConnectWallet"),
     path("DisconnectWallet/", views.disconnect_wallet, name="DisconnectWallet"),
     path("GenerateAddress/", views.generate_address, name="GenerateAddress"),

     path("Insurance/", views.insurance, name="Insurance"),
     path("BuySecurity/", views.buy_security, name="BuySecurity"),
     path("BuyProtection/<str:selected_plan>/", views.buy_protection_plan, name="BuyProtectionPlan"),

     path("MyAddresses/", views.my_addresses, name="MyAddresses"),
     path("MyTransactions/", views.my_transactions, name="MyTransactions"),

     path("Profile/", views.profile, name="Profile"),
     path("SwapCrypto/", views.swap_crypto, name="SwapCrypto"),
     path("Settings/", views.atm_settings, name="Settings"),
     
     path("SendCoinbaseWallet/", views.send_coinbase_wallet, name="SendCoinbaseWallet"),
     path("SendCryptoShareWallet/", views.send_cryptoshare_wallet, name="SendCryptoShareWallet"),

     path("SendCryptoShareCredits/", views.send_cryptoshare_credits, name="SendCryptoShareCredits"),
     path("RequestCryptoShareCredits/", views.request_cryptoshare_credits, name="RequestCryptoShareCredits"),

     path("SendMoneyConfirmation/", views.send_money_confirmation, name="SendMoneyConfirmation"),
     path("TransferMoney/", views.transfer_money, name="TransferMoney"),
     path("TransferCredits/", views.transfer_credits, name="TransferCredits"),

     #API ENDPOINTS
     path("SimpleSwapAPI/", views.simpleswap_api, name="SimpleSwapAPI"),
     path("GetCreditGrade/", views.get_credit_grade, name="GetCreditGrade"),
     path("GetAccountData/", views.get_account_data, name="GetAccountData"),
     path("CurrenciesWidget/", views.get_currencies_balance_widget, name="CurrenciesWidget"),


     #WEBHOOKS
     path("ConfirmationsCoinTransactions/", views.confirmations_coin_transactions, name="ConfirmationsCryptoTransactions"),
     path("ConfirmedCoinTransactions/", views.confirmed_coin_transactions, name="ConfirmedCoinTransactions"),
     path("ConfirmedTokenTransactions/", views.confirmed_token_transactions, name="ConfirmedTokenTransactions"),

     path("StripeWebhook/", views.stripe_webhook, name="StripeWebhook"),

     path("DailyRoutine/", views.daily_routine, name="DailyRoutine"),

     path("UpdateExchangeRates/", views.update_exchange_rates, name="UpdateExchangeRates"),

     path("RegisterWaitlistEmail/", views.register_waitlist_email, name="RegisterWaitlistEmail"),
     
     path("TestReceiver/", views.test_receiver, name="TestReceiver"),
     # path("TestClient/", views.test_client, name="TestClient")
     # path("NotificationService/", views.notification_service, name="NotificationService")
]

authentication/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from . import views

app_name = 'authentication'
urlpatterns = [
    path('', views.home, name='Home'),
    path('Email/', views.email, name='Email'),
    path('GiveBack/', views.give_back, name="GiveBack"),
    path('Verify/', views.verify, name='Verify'),
    path('Signing/', views.signing, name='Signing'),
    path('Registration/', views.registration, name='Registration'),
    path('PasswordReset', views.reset_password, name="PasswordReset"),
    path('Login/', views.views.login, name='Login'),
    path('Logout/', views.logout, name='Logout')
]

marketplace/urls.py
from django.urls import path
from . import views

app_name = "marketplace"

urlpatterns = [
    path("", views.marketplace, name="Marketplace"),
    path("purchase-history/", views.purchases_history, name="PurchaseHistory"),
    path("product/info/<int:id_product>/", views.product_info, name="ProductInfo"),  
    path("product/buy/<int:id_product>/", views.buy_product, name="ProductBuy"),  
]

marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from businesses.models import Business
from django.utils import timezone
from datetime import datetime, timedelta


class DigitalService(models.Model):
    id_product = models.AutoField(primary_key=True)
    name = models.CharField(max_length=30, null=True)
    price = models.DecimalField(max_digits=18, decimal_places=8)
    photo_url = models.CharField(max_length=255, null=True)      
    description = models.CharField(max_length=250, null=True)
    video_url = models.CharField(max_length=255, null=True)
    calendar_url = models.CharField(max_length=255, null=True)
    extra_url = models.CharField(max_length=255, null=True)

class Product(models.Model):
    id_product = models.AutoField(primary_key=True)
    business = models.ForeignKey(Business, on_delete = models.CASCADE)
    category = models.CharField(max_length=30)

    digital_service_reference = models.ForeignKey(DigitalService, on_delete = models.CASCADE, null = True)

class PurchaseHistory(models.Model):
    id_purchase = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete = models.SET_NULL, null=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    state = models.CharField(max_length=15)
    paid_price = models.DecimalField(max_digits=18, decimal_places=8)
    creation_datetime = models.DateTimeField(auto_now_add=True)

marketplace/views.py
from multiprocessing import context
from django.conf import settings as django_settings
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.http import Http404

from businesses.models import Business
from atm_functions.models import Balance, DigitalCurrency, DynamicUsername, Notification
from common.emails import sale_owner_notification
from .models import Product, PurchaseHistory

from decimal import Decimal

@login_required()
def marketplace(request):
    context = {}

    products = Product.objects.all().select_related("digital_service_reference")

    # for p in products: print(p.__dict__)

    context["products"] = products

    return render(request, 'marketplace/marketplace.html', context)

@login_required()
def product_info(request, id_product = None):
    context = {}

    if not Product.objects.filter(id_product = id_product).exists():
        raise Http404()

    product_info = Product.objects.get(id_product = id_product)
    product_info.object_reference = None

    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    if product_info.category == "CONSULTATIONS":
        # product_info.object_reference = product_info.consultations_reference
        product_info.object_reference = product_info.digital_service_reference #Missing to create consultations object

    elif product_info.category == "DIGITAL_SERVICES":
        product_info.object_reference = product_info.digital_service_reference

    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->

    context["product"] = product_info
    return render(request, 'marketplace/product_info.html', context)

@login_required()
def buy_product(request, id_product = None):
    if not Product.objects.filter(id_product = id_product).exists():
        raise Http404()

    if request.method == "GET":
        return redirect('marketplace:ProductInfo', id_product = id_product)

    context = {}
    
    product = Product.objects.get(id_product = id_product)

    if product.business.owner == request.user:
        messages.error(request, "You can't buy your own products", extra_tags='danger')
        return redirect('marketplace:ProductInfo', id_product = id_product)

    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    if product.category == "CONSULTATIONS":
        # product_info.object_reference = product_info.consultations_reference
        product.object_reference = product.digital_service_reference #Missing to create consultations object

    elif product.category == "DIGITAL_SERVICES":
        product.object_reference = product.digital_service_reference

    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->
    # <-------------------- THIS NEEDS TO BE IN A UTILITY FUNCTION -------------------->

    product_price = product.object_reference.price

    user_object = request.user
    cryptoshare_credits_object = DigitalCurrency.objects.get(symbol="CSC")

    user_balance = Balance.objects.get(email = user_object, digital_currency_name = cryptoshare_credits_object)

    if user_balance.amount < product_price:
        messages.error(request, "You don't have enough CSC to buy this product.", extra_tags='danger')
        return redirect('marketplace:ProductInfo', id_product = id_product)
    
    user_balance.amount -= Decimal(product_price)
    user_balance.save()

    if product.category == "DIGITAL_SERVICES":
        purchase_state = "PENDING"
        success_message = "You have successfully bought this digital service, the seller will contact you soon."
    elif product.category == "CONSULTATIONS":
        purchase_state = "PENDING"
        success_message = "You have successfully bought this consultation, the seller will contact you soon."

    else:
        purchase_state = "COMPLETED"
        success_message = "You have successfully bought this product."

    purchase_registry = PurchaseHistory.objects.create(
        product = product,
        user = user_object,
        state = purchase_state,
        paid_price = product_price
    )

    # sale_owner_notification(sender_email, business_name, id_business, id_product, date, client_email)
    sale_owner_notification(
        sender_email = str(product.business.owner),
        business_name = product.business.official_name,
        id_business = product.business.id_business,
        id_product = product.id_product,
        date = purchase_registry.creation_datetime,
        client_email = str(user_object)
    )

    Notification.objects.create(
                user = product.business.owner,
                notification_lob = "BUSINESS",
                notification_type = "SALE",
                notification_state = "PENDING",
                description = f"You just sold a product / service from your {product.business.official_name} business."
            )

    messages.success(request, success_message)
    return redirect('marketplace:PurchaseHistory')

@login_required()
def purchases_history(request):

    context = {}

    purchases_history = PurchaseHistory.objects.filter(user = request.user)
    context["purchases_history"] = purchases_history

    return render(request, 'marketplace/purchase_history.html', context)

    pass

templates/marketplace/marketplace_sidebar.html
{% load static %}
{% static "images" as baseUrl %}
{% if request.user.is_authenticated %}
{% include 'a_sessiontimeout.html' %}
{% include 'includes/notifications_sidebar.html' %}
{% endif %}

{% include 'includes/notifications_sidebar.html' %}
        <!--========== BOX ICONS ==========-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <!--========== HEADER ==========-->
    <header class="header">
        <div class="header__container">
            <img src="{% static '/images/logo.png' %}" alt="" class="header__img" onclick='location.href="{% url 'atm_functions:Home' %}"'>

            {% if request.user.is_authenticated %}

            {% include 'currencies_widget.html' %}
            {% endif %}


            <div class="header__toggle">
                <i class='bx bx-menu' id="header-toggle" style="color: white;"></i>
            </div>
        </div>
    </header>


<br>
<div class="nav" id="navbar">
    <nav class="nav__container">
        <div>           
            <div class="nav__items nav__logo">
                <!-- <a href="{% url 'atm_functions:Home' %}" class="sidebar-logo"><img src="{% static '/images/logo.png' %}"></a> -->

                {% if request.user.is_authenticated %}
    
                <span class="nav__logo-name mt-2" id="credit_grade" style="color: white;"><b>CREDIT GRADE: </b></span>
    
                <span class="nav__name" ><a href="{% url 'atm_functions:BuildCredit' %}">(Improve Credit Grade)</a></span>

                <a class="btn btn-primary nav__name" data-bs-toggle="offcanvas" href="#offcanvasRight" role="button" aria-controls="offcanvasRight">
                    <i class='bx bxs-bell' style="color: gold;"></i>
                </a>
                {% endif %}

            </div>

            <div class="nav__list">
                <div class="nav__items">
                    <a href="{% url 'atm_functions:Home' %}" class="nav__link">
                        <i class='nav__icon bx bx-arrow-back' style="color: gold;"></i>
                        <span class="nav__name">GO BACK</span>
                    </a>
                </div>
                <div class="nav__items">
                    <h3 class="nav__subtitle">MARKETPLACE</h3>

                    <a href="{% url 'marketplace:Marketplace' %}" class="nav__link">
                        <i class="nav__icon bx bxs-home" style="color: gold;"></i>
                        <span class="nav__name">HOME</span>
                    </a>

                    <a href="{% url 'marketplace:PurchaseHistory' %}" class="nav__link">
                        <i class="nav__icon bx bx-history" style="color: gold;"></i>
                        <span class="nav__name">MY PURCHASES</span>
                    </a>

                </div>
            </div>
        </div>

        {% if request.user.is_authenticated %}
        <form action="{% url 'authentication:Logout' %}" id="logout" method="POST">
            {% csrf_token %}
        </form>
        <a onclick="$('#logout').submit();" href="#logout" class="nav__link nav__logout">
            <i class='bx bx-log-out nav__icon' ></i>
                <span class="nav__name">Log Out</span>
        </a>
        
        {% endif %}
    </nav>
</div>
{% include 'crisp_client.html' %}

    
<script type="text/javascript">
    window.onload = function() {
        // console.log(localStorage.hideAlert);
        // if (!localStorage.hideAlert) {
        //     $('#DepositWarning').modal('toggle');
        // }
        if ({{ request.user.is_authenticated|yesno:"true,false" }}){
            GetCreditGrade();
            GetNotifications();
        }
    }

    function neverShowAgainModal() {
        localStorage.setItem('hideAlert', true);
        $("#DepositWarning").modal('hide');
    };

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != "") {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
                }
            }
        }
        return cookieValue;
    }
    // document.getElementById("pay_amount").innerHTML = "Amount : "+ offerAmount;

    function GetCreditGrade(){
        var url = "{% url 'atm_functions:GetCreditGrade' %}";
        var data = {
            csrfmiddlewaretoken: getCookie('csrftoken')
        };
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            success: function(response){
                document.getElementById("credit_grade").innerHTML = "CREDIT GRADE: "+ response["credit_grade"];
            },
            error: function(response){
                document.getElementById("credit_grade").innerHTML = "CREDIT GRADE: ERROR";
            }
        });
    };
</script>
<script src="{% static 'js/sidebar.js' %}"></script>


<style>
    .sidebarCoin {
        height: 20px;
        width: auto;
        position: relative;
        padding-left: 5px;
    }
</style>

templates/marketplace/product_info.html
{% load static %}
{% load tz %}
{% static "images" as baseUrl %}

<!doctype html>
<html lang="en">
{% include 'header.html' %}

<body>
    {% include 'marketplace/marketplace_sidebar.html' %}
    <div class="content-container">
        {% include 'messages.html' %}
        {% include 'a_sessiontimeout.html' %}
        <br>
        <div class="container">
            <div class="row gy-5">
                <div class="col-md-9">
                    <div class="m-1 p-2 text-center">
                        <h4>
                            {{ product.object_reference.name }}
                        </h4>
                    </div>
                    {% if product.object_reference.photo_url %}
                    <img src="{{ product.object_reference.photo_url }}"
                            class="d-block w-auto mx-auto" alt="...">
                    {% endif %}

                </div>
                <!-- <div class="col-md-3 border border-info bg-light" style="border-radius: 5%;"> -->
                <div class="card col-md-3 border border-info bg-light text-center" style="border-radius: 5%;">
                    <div class="card-body">
                        <h6 class="card-subtitle mb-2 text-muted">
                            <u>
                                {{ product.business.official_name }}
                            </u>
                        </h6>
                        <h5 class="card-title">
                            {{ product.object_reference.price | floatformat:2 }}
                        </h5>

                        <p class="card-text">
                            {{ product.object_reference.description }}
                        </p>
                    </div>
                    
                    <div class="card-footer bg-transparent">
                        <form action="{% url 'marketplace:ProductBuy' id_product=product.id_product %}" method="POST">
                            {% csrf_token %}
                            <button style=text-align:center class="btn btn-primary" type="submit" id="button_details">
                                Buy
                            </button>
                        </form>
                    </div>
                </div>
<!-- 
                    <div class="m-1 p-2 text-center">
                        <h6>
                            {{ product.object_reference.price }}
                        </h6>
                    </div>
                    <div class="m-1 p-2 text-start">
                        {{ product.object_reference.description }}
                    </div>
                    <div class="col d-flex justify-content-center align-items-end">
                        <button class="btn btn-primary" type="button">
                          Bottom Center
                        </button>
                    </div> -->

                <!-- </div> -->
    
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en',
                autoDisplay: false
            }, 'google_translate_element'); //remove the layout
        }
    </script>
    <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript">
    </script>


    <script type="text/javascript">
        function triggerHtmlEvent(element, eventName) {
            var event;
            if (document.createEvent) {
                event = document.createEvent('HTMLEvents');
                event.initEvent(eventName, true, true);
                element.dispatchEvent(event);
            } else {
                event = document.createEventObject();
                event.eventType = eventName;
                element.fireEvent('on' + event.eventType, event);
            }
        }

        $('.translation-links a').click(function (e) {
            e.preventDefault();
            var lang = $(this).data('lang');
            $('#google_translate_element select option').each(function () {
                if ($(this).text().indexOf(lang) > -1) {
                    $(this).parent().val($(this).val());
                    var container = document.getElementById('google_translate_element');
                    var select = container.getElementsByTagName('select')[0];
                    triggerHtmlEvent(select, 'change');
                }
            });
        });
    </script>
</body>

</html>

templates/marketplace/purchase_history.html
{% load static %}
{% static "images" as baseUrl %}

<!doctype html>
<html lang="en">
{% include 'header.html' %}

<body>
    {% include 'marketplace/marketplace_sidebar.html' %}
    {% if auth_level > 0 %}
    {% include 'a_sessiontimeout.html' %}
    {% endif %}
    <div class="content-container">
        {% include 'messages.html' %}
        <h2 class="ml-4">Purchase History</h2>
        
        <div class="container table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <!-- <th scope="col">#</th> -->
                        <th scope="col">Order ID</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Business Name</th>
                        <th scope="col">State</th>
                        <th scope="col">Price</th>
                        <th scope="col">Date</th>
                        <th scope="col" class="align-middle" style="text-align: center;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for purchase in purchases_history %}
                    <tr>
                        <td>{{ purchase.id_purchase }}</td>
                        {% if purchase.product.category == "DIGITAL_SERVICES" %}
                        <td>{{ purchase.product.digital_service_reference.name }}</td>
                        {% else %}
                        <td>NOT AVAILABLE</td>
                        {% endif %}
                        <td>{{ purchase.product.business.official_name }}</td>
                        <td>{{ purchase.state }}</td>
                        <td>{{ purchase.paid_price | floatformat:2 }}</td>
                        <td>{{ purchase.creation_datetime }} UTC</td>
                        <td class="align-middle" style="text-align: center;">
                            <!-- <form action="" method="POST"> -->
                                <!-- {% csrf_token %} -->
                            <button style=text-align:center class="btn btn-outline-primary bg-danger text-light disabled" type="submit" id="file_claim">
                                FILE A CLAIM
                            </button>
                            <!-- </form> -->
                        </td>
                    </tr>
                    {% endfor %}
    
                    
                </tbody>
            </table>
        </div>

    </div>


    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en',
                autoDisplay: false
            }, 'google_translate_element'); //remove the layout
        }
    </script>
    <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript">
    </script>


    <script type="text/javascript">
        function triggerHtmlEvent(element, eventName) {
            var event;
            if (document.createEvent) {
                event = document.createEvent('HTMLEvents');
                event.initEvent(eventName, true, true);
                element.dispatchEvent(event);
            } else {
                event = document.createEventObject();
                event.eventType = eventName;
                element.fireEvent('on' + event.eventType, event);
            }
        }

        $('.translation-links a').click(function (e) {
            e.preventDefault();
            var lang = $(this).data('lang');
            $('#google_translate_element select option').each(function () {
                if ($(this).text().indexOf(lang) > -1) {
                    $(this).parent().val($(this).val());
                    var container = document.getElementById('google_translate_element');
                    var select = container.getElementsByTagName('select')[0];
                    triggerHtmlEvent(select, 'change');
                }
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $('[data-bs-toggle="popover"]').popover();
        });
    </script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
<div class="position-fixed top-0 end-0" style="z-index: 10000">
    <div id="ClipboardAlert" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <strong class="me-auto">Copied to clipboard</strong>
            <small>Now</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
            The username has been copied to your clipboard.
        </div>
    </div>
</div>

</html>

<!-- Modal -->
<div class="modal fade" id="BuyUsername" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">BUY NEW USERNAME</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'atm_functions:Profile' %}?action=BuyUsername" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <p>Buying and modifying personalized username has a cost of:</p>
                    <p class="text-info" style="text-align: center;">
                        <b>
                            10 CryptoshareCredits
                        </b>
                    </p>
                    <div class="mb-3">
                        <p style="text-align: center;">Please enter your new username</p>
                        <input type="text" class="form-control text-center" id="newUsername" name="newUsername"
                            placeholder="Your new username" maxlength="30">
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success" id="NeverShowAgain">
                        Change Username
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>