ATM/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls.conf import include

urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('atm/', include('atm_functions.urls', namespace='atm_functions')),
    path('businesses/', include('businesses.urls', namespace='businesses')),
    path('webhooks/', include('webhooks.urls', namespace='webhooks')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('cryptosharepay/', include('cryptosharepay.urls', namespace='cryptosharepay')),
    # path('admin/', admin.site.urls),
]

businesses/urls.py
from django.urls import path
from . import views

app_name = "businesses"

urlpatterns = [
    path("", views.businesses, name="Businesses"),
    path("create/", views.create_business, name="Create"),
    path("manage/", views.manage_businesses, name="Manage"),
    path("manage/<int:id_business>/", views.manage_business, name="ManageBusiness"),
    path("edit/", views.edit_business, name="Edit"),
    path("search/", views.search_business, name="Search"),

    path("manage/<int:id_business>/sales/", views.manage_sales, name="ManageSales"),
    path("manage/<int:id_business>/sales/messages/<int:id_purchase>", views.sale_messages, name="SaleMessages"),
    path("manage/<int:id_business>/sales/messages/<int:id_purchase>/send", views.sale_send_message, name="SaleSendMessage"),

    path("create/product/<int:id_business>/", views.create_product, name="CreateProduct"),
    path("delete/product/<int:id_business>/<int:id_product>/", views.delete_product, name="DeleteProduct"),
    path("manage/product/<int:id_business>/", views.manage_products, name="ManageProduct"),

]

businesses/models.py
from django.db import models
from django.contrib.auth.models import User
# from marketplace.models import PurchaseHistory

# Create your models here.


class Business(models.Model):
    id_business = models.AutoField(primary_key=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_owner')
    official_name = models.CharField(max_length=57)
    system_name = models.CharField(max_length=57)
    logo_url = models.CharField(max_length=255, null=True)
    category = models.CharField(max_length=30)
    system_category = models.CharField(max_length=30, null=True)
    creation_datetime = models.DateTimeField(auto_now_add=True)


class BusinessMessages(models.Model):
    id_message = models.AutoField(primary_key=True)
    id_purchase = models.ForeignKey("marketplace.PurchaseHistory", on_delete=models.CASCADE)
    message_sender = models.CharField(max_length=20, null=True)
    message = models.TextField(null=True, blank=True)
    creation_datetime = models.DateTimeField(auto_now_add=True)

businesses/views.py
from django.conf import settings as django_settings
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.http import Http404

from common.emails import sale_business_send_message

from .models import Business, BusinessMessages
from atm_functions.models import Balance, DigitalCurrency, DynamicUsername
from marketplace.models import Product, DigitalService, PurchaseHistory

from decimal import Decimal

# Create your views here.


@login_required()
def businesses(request):
    businesses = Business.objects.all()

    context = {
            'businesses': businesses
            }
            
    return render(request, 'businesses/businesses.html', context)

@login_required()
def manage_sales(request, id_business):

    context = {}

    business = Business.objects.get(
        id_business = id_business
        )

    business_sales = PurchaseHistory.objects.filter(
        product__business = business
        )

    context["business"] = business
    context["business_sales"] = business_sales

    return render(request, 'businesses/sales/manage_sales.html', context)

    pass

@login_required()
def create_business(request):

    if request.method == "GET":
        return render(request, 'businesses/create_business.html')

    if request.method == "POST":
        business_official_name = request.POST.get("business_name", None)
        business_username = request.POST.get("business_username", None).lower().replace(" ", "")
        business_system_name = business_official_name.lower()
        business_category = request.POST.get("business_category", None)
        business_price = 50      #PRICE IN CRYPTOSHARECREDITS

        business_username = business_username.replace(" ", "")

        if DynamicUsername.objects.filter(id_username=business_username).exists():
            messages.warning(request, "Username already exists.")

            return redirect('businesses:Create')

        name_exists = Business.objects.filter(system_name=business_system_name)
        if name_exists:
            messages.info(request, "Business name already exists.")
            return redirect('businesses:Create')

        digital_currency_object = DigitalCurrency.objects.get(symbol="CSC")
        user_balance = Balance.objects.get(email = request.user, digital_currency_name = digital_currency_object)

        if user_balance.amount < business_price:
            messages.info(request, "You do not have enough funds to create a business. Please buy more CryptoshareCredits.")
            return redirect('atm_functions:Home')
        
        user_balance.amount -= Decimal(business_price)
        user_balance.save()

        new_business = Business(owner=request.user, official_name=business_official_name, system_name=business_system_name, category=business_category)
        new_business.save()

        new_username = DynamicUsername.objects.create(
            id_username = business_username,
            username_type = "BUSINESS",
            business_reference = new_business
        )

        messages.info(request, "Business created successfully.")
        return redirect('businesses:Businesses')

@login_required()
def edit_business(request):

    business_id = request.GET.get("id", None)

    if not business_id:
        return redirect('businesses:Manage')

    if not Business.objects.filter(id_business=business_id).exists():
        return redirect('businesses:Manage')

    business = Business.objects.get(id_business=business_id)

    if request.method == "GET":

        if business.system_name:
            business.system_name = business.system_name.replace(" ", "-")

        context = {
            'business': business
        }

        return render(request, 'businesses/edit_businesses.html', context)
    
    if request.method == "POST":
        
        business_id = int(request.POST.get("business_id", None))
        business_category = request.POST.get("business_category", None)
        business_logo_url = request.POST.get("business_logo", None)

        if len(business_logo_url) > 255:
            messages.info(request, "Image name is too long, please rename it and try again.")
            return redirect('businesses:Edit')

        business = Business.objects.get(id_business=business_id)
        business.category = business_category
        business.logo_url = business_logo_url
        business.save()

        messages.info(request, "Business updated successfully.")
        return redirect('businesses:Manage')

    return render(request, 'businesses/edit_businesses.html')


@login_required()
def manage_businesses(request):
    businesses = Business.objects.filter(owner=request.user)

    context = {
        "businesses": businesses
    }

    return render(request, 'businesses/manage_businesses.html', context)

@login_required()
def manage_business(request, id_business = None):

    if not Business.objects.filter(id_business = id_business, owner = request.user).exists():
        raise Http404()

    context = {}

    business = Business.objects.get(id_business = id_business)

    context["business"] = business

    return render(request, 'businesses/manage_business.html', context)

@login_required()
def search_business(request):

    if request.method == "GET":
        businesses = Business.objects.all()

    if request.method == "POST":                
        search_option = request.POST.get("SearchOption", None)
        search_value = request.POST.get("SearchValue", None)

        if search_option == "StartsWith":
            businesses = Business.objects.filter(system_name__startswith=search_value.lower())

        elif search_option == "Contains":
            businesses = Business.objects.filter(system_name__contains=search_value.lower())

        elif search_option == "ExactMatch":
            businesses = Business.objects.filter(system_name=search_value.lower())

    context = {
        "businesses": businesses
    }

    return render(request, 'businesses/search_businesses.html', context)


@login_required()
def create_product(request, id_business = None):

    if not Business.objects.filter(id_business = id_business, owner = request.user).exists():
        raise Http404()

    context = {}

    business = Business.objects.get(id_business = id_business)

    if request.method == "GET":

        context["business"] = business

        return render(request, 'businesses/products/create_product.html', context)

    elif request.method == "POST":                  
        product_name = request.POST.get("product_name", None)
        product_photo_url = request.POST.get("product_photo", None)
        product_price = request.POST.get("product_price", None)
        product_description = request.POST.get("product_description", None)
        product_extra = request.POST.get("product_extra", None)

        if business.system_category == "DIGITAL_SERVICES":

            product_video_url = request.POST.get("product_video", None)
            product_calendar_url = request.POST.get("product_calendar", None)

            new_digital_service = DigitalService.objects.create(
                name = product_name,
                price = product_price,
                photo_url = product_photo_url,
                description = product_description,
                video_url = product_video_url,
                calendar_url = product_calendar_url,
                extra_url = product_extra
            )

            new_product = Product.objects.create(
                business = business,
                category = business.system_category,
                digital_service_reference = new_digital_service
            )
        
        messages.success(request, "Product created successfully.")

        return redirect('businesses:ManageBusiness', id_business=business.id_business)

@login_required()
def delete_product(request, id_business = None, id_product = None):
    if not Product.objects.filter(id_product = id_product, business__owner = request.user).exists():
        messages.error(request, "You can't do that!", extra_tags='danger')

        return redirect('businesses:ManageProduct')


    product = Product.objects.get(id_product = id_product, business__owner = request.user)

    if product.category == "DIGITAL_SERVICES":
        inner_product = product.digital_service_reference

    product.delete()

    messages.success(request, "Product deleted successfully.")

    return redirect('businesses:ManageProduct', id_business=id_business)

@login_required()
def manage_products(request, id_business = None):
    if not Business.objects.filter(id_business = id_business, owner = request.user).exists():
        raise Http404()

    context = {}

    business = Business.objects.get(id_business = id_business)

    if request.method == "GET":

        products = Product.objects.filter(business = business)

    context["business"] = business
    context["products"] = products

    return render(request, 'businesses/products/manage_products.html', context)

@login_required()
def sale_messages(request, id_business = None, id_purchase = None):
    if not Business.objects.filter(id_business = id_business, owner = request.user).exists() or not PurchaseHistory.objects.filter(id_purchase = id_purchase, product__business__id_business = id_business).exists():
        raise Http404()

    context = {}

    business = Business.objects.get(id_business = id_business)

    business_messages = BusinessMessages.objects.filter(
        id_purchase = id_purchase
    )

    context["business"] = business
    context["id_purchase"] = id_purchase
    context["business_messages"] = business_messages

    return render(request, 'businesses/sales/sale_messages.html', context)

def sale_send_message(request, id_business = None, id_purchase = None):
    print("TEST")

templates/businesses/sales/manage_sales.html
{% load static %}
{% load tz %}
{% static "images" as baseUrl %}

<!doctype html>
<html lang="en">
{% include 'header.html' %}
<body>
    {% include 'businesses/businesses_sidebar.html' %}

    <div class="content-container">
        {% include 'messages.html' %}

        <h2 class="ml-4 text-primary">{{ business.official_name }} products</h2>
        <br>
        <div class="container table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <!-- <th scope="col">#</th> -->
                        <th scope="col">Order ID</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">State</th>
                        <th scope="col">Price</th>
                        <th scope="col">Date</th>
                        <th scope="col" class="align-middle" style="text-align: center;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for sale in business_sales %}
                    <tr>
                        <td>{{ sale.id_purchase }}</td>
                        {% if sale.product.category == "DIGITAL_SERVICES" %}
                        <td>{{ sale.product.digital_service_reference.name }}</td>
                        {% else %}
                        <td>NOT AVAILABLE</td>
                        {% endif %}
                        <td>{{ sale.state }}</td>
                        <td>{{ sale.paid_price | floatformat:2 }}</td>
                        <td>{{ sale.creation_datetime }} UTC</td>
                        <td class="align-middle" style="text-align: center;">
                            <!-- <form action="" method="POST"> -->
                                <!-- {% csrf_token %} -->
                            <a class="btn btn-info bg-info text-light" href="{% url 'businesses:SaleMessages' id_business=sale.product.business.id_business id_purchase=sale.id_purchase %}" role="button">MESSAGES</a>

                            <button style=text-align:center class="btn btn-primary bg-warning text-light disabled" type="submit" id="file_claim">
                                FILE A CLAIM
                            </button>
                            <!-- </form> -->

                            <!-- <form action="" method="POST"> -->
                                <!-- {% csrf_token %} -->
                                <button style=text-align:center class="btn btn-primary bg-danger text-light disabled" type="submit" id="file_claim">
                                    REFUND
                                </button>
                                <!-- </form> -->
                        </td>
                    </tr>
                    {% endfor %}
                    {% if not business_sales %}
                        <tr>
                            <th scope="row" style="text-align: center;" colspan="4">No sales</th>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en',
                autoDisplay: false
            }, 'google_translate_element'); //remove the layout
        }
    </script>
    <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript">
    </script>
    
    
    <script type="text/javascript">
        function triggerHtmlEvent(element, eventName) {
            var event;
            if (document.createEvent) {
                event = document.createEvent('HTMLEvents');
                event.initEvent(eventName, true, true);
                element.dispatchEvent(event);
            } else {
                event = document.createEventObject();
                event.eventType = eventName;
                element.fireEvent('on' + event.eventType, event);
            }
        }
        
        $('.translation-links a').click(function (e) {
            e.preventDefault();
            var lang = $(this).data('lang');
            $('#google_translate_element select option').each(function () {
                if ($(this).text().indexOf(lang) > -1) {
                    $(this).parent().val($(this).val());
                    var container = document.getElementById('google_translate_element');
                    var select = container.getElementsByTagName('select')[0];
                    triggerHtmlEvent(select, 'change');
                }
            });
        });
    </script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/businesses/sales/sale_messages.html
{% load static %}
{% load tz %}
{% static "images" as baseUrl %}

<!doctype html>
<html lang="en">
{% include 'header.html' %}
<body>
    {% if iframe is None %}
    {% include 'businesses/businesses_sidebar.html' %}
    {% endif %}
    <div class="content-container">
        {% include 'messages.html' %}
        {% include 'a_sessiontimeout.html' %}
        <h2 class="ml-4 text-primary">Message your customer</h2>
        <br>
        <form action="{% url 'businesses:SaleSendMessage' id_business=business.id_business id_purchase=id_purchase %}" method="post">
            {% csrf_token %}
            <div class="form-group col-md-12">
                <label for="business_name"><b>Type a new message for your customer</b></label>
                <textarea class="form-control" id="message_text" name="message" rows="3"></textarea>
            </div>
            <div class="d-grid col-6 mx-auto">
                <button type="submit" class="btn btn-primary">Send Message</button>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en',
                autoDisplay: false
            }, 'google_translate_element'); //remove the layout
        }
    </script>
    <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript">
    </script>
    
    
    <script type="text/javascript">
        function triggerHtmlEvent(element, eventName) {
            var event;
            if (document.createEvent) {
                event = document.createEvent('HTMLEvents');
                event.initEvent(eventName, true, true);
                element.dispatchEvent(event);
            } else {
                event = document.createEventObject();
                event.eventType = eventName;
                element.fireEvent('on' + event.eventType, event);
            }
        }
        
        $('.translation-links a').click(function (e) {
            e.preventDefault();
            var lang = $(this).data('lang');
            $('#google_translate_element select option').each(function () {
                if ($(this).text().indexOf(lang) > -1) {
                    $(this).parent().val($(this).val());
                    var container = document.getElementById('google_translate_element');
                    var select = container.getElementsByTagName('select')[0];
                    triggerHtmlEvent(select, 'change');
                }
            });
        });
    </script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>