ATM/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls.conf import include

urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('atm/', include('atm_functions.urls', namespace='atm_functions')),
    path('businesses/', include('businesses.urls', namespace='businesses')),
    path('webhooks/', include('webhooks.urls', namespace='webhooks')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('cryptosharepay/', include('cryptosharepay.urls', namespace='cryptosharepay')),
    # path('admin/', admin.site.urls),
]

atm_functions/urls.py
from django.urls import path
from . import views

app_name = "atm_functions"
urlpatterns = [
     path("", views.home, name="Home"),
     path("ApproveWallet/", views.approve_wallet, name="ApproveWallet"),

     path("Contacts/", views.contacts, name="Contacts"),
     path("Contacts/Create", views.create_contact, name="CreateContact"),
     path("Contacts/Delete", views.delete_contact, name="DeleteContact"),

     path("Referrals/", views.referrals, name="Referrals"),
     path("ReferralsAdmin/", views.referrals_admin, name="ReferralsAdmin"),

     # path("EstateNetWorth/", views.estate_net_worth, name="EstateNetWorth"),
     # path("EditEstateNetWorth/", views.edit_estate_net_worth, name="EditEstateNetWorth"),

     # path("BlockchainWills/", views.blockchain_wills, name="BlockchainWills"),
     # path("RegisterBlockchainWill/", views.register_blockchain_will, name="RegisterBlockchainWill"),
     # path("CertificateBlockchainWill/", views.certificate_blockchain_will, name="CertificateBlockchainWill"),     
     # path("CertificateBlockchainWill/<int:id>/", views.certificate_blockchain_will, name="CertificateBlockchainWill"),    

     path("BuyCrypto/", views.buy_crypto, name="BuyCrypto"),
     path("BuildCredit/", views.buy_credit, name="BuildCredit"),
     path("BuyCryptoWidget/", views.buy_crypto_widget, name="BuyCryptoWidget"),

     path("BuildCreditCrypto/<str:code>/", views.buy_credit_with_crypto, name="BuildCreditCrypto"),

     path("CheckCredit/", views.check_balance, name="CheckCredit"),
     path("CreditGrades/", views.credit_grades, name="CreditGrades"),
     path("CryptoShareWallet/", views.cryptoshare_wallet, name="CryptoShareWallet"),

     path("CreditRatings/", views.credit_rankings, name="CreditRatings"),

     path("StripeCheckout/", views.stripe_checkout, name="StripeCheckout"),
     path("StripeCheckoutResult/", views.stripe_checkout_result, name="StripeCheckoutResult"),

     path("CryptoNews/", views.crypto_news, name="CryptoNews"),

     path("ConnectWallet/", views.connect_wallet, name="ConnectWallet"),
     path("DisconnectWallet/", views.disconnect_wallet, name="DisconnectWallet"),
     path("GenerateAddress/", views.generate_address, name="GenerateAddress"),

     path("Insurance/", views.insurance, name="Insurance"),
     path("BuySecurity/", views.buy_security, name="BuySecurity"),
     path("BuyProtection/<str:selected_plan>/", views.buy_protection_plan, name="BuyProtectionPlan"),

     path("MyAddresses/", views.my_addresses, name="MyAddresses"),
     path("MyTransactions/", views.my_transactions, name="MyTransactions"),

     path("Profile/", views.profile, name="Profile"),
     path("SwapCrypto/", views.swap_crypto, name="SwapCrypto"),
     path("Settings/", views.atm_settings, name="Settings"),
     
     path("SendCoinbaseWallet/", views.send_coinbase_wallet, name="SendCoinbaseWallet"),
     path("SendCryptoShareWallet/", views.send_cryptoshare_wallet, name="SendCryptoShareWallet"),

     path("SendCryptoShareCredits/", views.send_cryptoshare_credits, name="SendCryptoShareCredits"),
     path("RequestCryptoShareCredits/", views.request_cryptoshare_credits, name="RequestCryptoShareCredits"),

     path("SendMoneyConfirmation/", views.send_money_confirmation, name="SendMoneyConfirmation"),
     path("TransferMoney/", views.transfer_money, name="TransferMoney"),
     path("TransferCredits/", views.transfer_credits, name="TransferCredits"),

     #API ENDPOINTS
     path("SimpleSwapAPI/", views.simpleswap_api, name="SimpleSwapAPI"),
     path("GetCreditGrade/", views.get_credit_grade, name="GetCreditGrade"),
     path("GetAccountData/", views.get_account_data, name="GetAccountData"),
     path("CurrenciesWidget/", views.get_currencies_balance_widget, name="CurrenciesWidget"),


     #WEBHOOKS
     path("ConfirmationsCoinTransactions/", views.confirmations_coin_transactions, name="ConfirmationsCryptoTransactions"),
     path("ConfirmedCoinTransactions/", views.confirmed_coin_transactions, name="ConfirmedCoinTransactions"),
     path("ConfirmedTokenTransactions/", views.confirmed_token_transactions, name="ConfirmedTokenTransactions"),

     path("StripeWebhook/", views.stripe_webhook, name="StripeWebhook"),

     path("DailyRoutine/", views.daily_routine, name="DailyRoutine"),

     path("UpdateExchangeRates/", views.update_exchange_rates, name="UpdateExchangeRates"),

     path("RegisterWaitlistEmail/", views.register_waitlist_email, name="RegisterWaitlistEmail"),
     
     path("TestReceiver/", views.test_receiver, name="TestReceiver"),
     # path("TestClient/", views.test_client, name="TestClient")
     # path("NotificationService/", views.notification_service, name="NotificationService")
]

templates/a_sessiontimeout.html
<div class="modal fade" id="myModal" data-bs-keyboard="false" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Session Timeout Notice</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <p>For your security, your session will time out after 1 minute.</p>
            <b><p>To stay signed in, click the &times; in the corner, or anywhere outside of this window.</p></b>
        </div>
      </div>
    </div>
</div>
<script>
    // https://stackoverflow.com/questions/23023916/how-to-implement-auto-logout-in-javascript
    var logoutWarn = 1000*60*4; // make logout notice appear after 4 minutes
    var logoutNow = 1000*60; // log out 1 minute after notice appears
    
    var warningTimer;
    var timeoutTimer;

    // start the timer for idling
    function startWarningTimer() {
        warningTimer = setTimeout("idleWarning()", logoutWarn);
    }
    // set timer when page is first opened
    startWarningTimer();

    // reset the timers
    function resetTimers() {
        clearTimeout(timeoutTimer);
        startWarningTimer();
    }
    // show modal
    function idleWarning() {
        clearTimeout(warningTimer);
        timeoutTimer = setTimeout("idleLogout()", logoutNow);
        $('#myModal').modal('toggle');
    }

    // function to redirect to logout page
    // called 1 minute after modal appears
    var idleLogout = function() {
        window.location.href = '/Logout/';
    }

    // Get the modal
    var modal = document.getElementById("myModal");
    
    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");
    
    // Get the span element that closes the modal
    var span = document.getElementsByClassName("btn-close")[0];
    
    // When the user clicks on (x), close the modal
    // Reset the logout timer
    span.onclick = function() {
        resetTimers();
    }
    
    // When the user clicks anywhere outside of the modal, close it
    // Reset the logout timer
    window.onclick = function(event) {
        if (event.target == modal) {
            resetTimers();
        }
    }
    document.onclick= function(event) {
        resetTimers();
    };
</script>

templates/atm_user_profile.html
{% load static %}
{% static "images" as baseUrl %}

<!doctype html>
<html lang="en">
{% include 'header.html' %}
<body>
    {% include 'atm_sidebar.html' %}
    {% if auth_level > 0 %}
    {% include 'a_sessiontimeout.html' %}
    {% endif %}
    <div class="content-container">
        {% include 'messages.html' %}
        <h2 class="ml-4">User Profile</h2>
        <div class="text-center" style="margin-top: 5%;">
            <img src="{% static '/images/logo.png' %}" class="rounded-circle border-primary"  style="height: 200px; width: auto;"" alt="...">
        </div>
        

        <div class="container text-center">

            <div class="card text-white bg-primary m-3">
                <h3 class="card-header">Crypto$hare Usernames</h3>
                <div class="card-body">

                    <h5 class="card-title m-2">Personal Username</h5>
                    <i class="fa-solid fa-circle-question" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-trigger="hover focus" title="Referral Code" data-bs-content="You can use your username as a Referral Code and get 10 CryptoshareCredits for each user that signs up!"></i>
                    <div class="form-group">
                        <div class="list-group">                            
                            <button type="button" class="list-group-item list-group-item-action" onclick="$('#ClipboardAlert').toast('show'); navigator.clipboard.writeText('{{ user.system_username }}');">
                                {{ user.system_username }}
                            </button>
                        </div>
                        <div class="mx-auto m-3">
                            <button type="button" class="btn btn-info" id="submit" onclick="$('#BuyUsername').modal('toggle');">Change Personal Username</button>
                        </div>
                    </div>

                    <h5 class="card-title m-2">Business Usernames</h5>
                    <div class="form-group">
                        <div class="list-group">
                            {% for username in usernames %}
                                <button type="button" class="list-group-item list-group-item-action" onclick="$('#ClipboardAlert').toast('show'); navigator.clipboard.writeText('{{ username.id_username }}');">
                                    {{ username.id_username }}
                                </button>
                            {% endfor %}
                        </div>
                    </div>

                    <p class="card-text">
                        You can use this usernames for receiving payments.
                    </p>
                </div>
            </div>

            <div class="card text-white bg-primary m-3">
                <h3 class="card-header">Personal Information</h3>
                <div class="card-body">
                    <form action="{% url 'atm_functions:Profile' %}?action=UpdateProfileInfo" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="first_name">First Name</label>
                            <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user.user.first_name }}" required>
                        </div>
                        <div class="form-group">
                            <label for="last_name">Last Name</label>
                            <input type="text" class="form-control" id="last_name" name="last_name" value="{{ user.user.last_name }}" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{ user.user.email }}" readonly disabled>
                        </div>
                        <div class="form-group">
                            <label for="country">Country</label>
                                <select type="text" class="form-control" name="country" id="country" required {% if request.session.country_code == "US" %} readonly disabled {% endif %}>
                                <!-- If user.country is none, put select country -->
                                {% if user.user.country is none %}
                                    <option value="" disabled selected>Select Country</option>
                                {% endif %}
                                {% for country in countries %}
                                <option value="{{ country.0 }}" {% if user.country == country.0 %}selected{% endif %}>{{ country.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% if user.state is not none %}
                        <div class="form-group">
                            <label for="state">State</label>
                            <input type="text" class="form-control" id="state" name="state" value="{{ user.state }}" required>
                        </div>
                        {% endif %}
                        <div class="form-group">
                            <label for="birthdate">Birthdate</label>
                            <input type="date" class="form-control" id="birthdate" name="birthdate" value="{{ user.birthdate|date:'Y-m-d'|default:'' }}" onkeydown="event.preventDefault()" required>
                        </div>
                        <!-- 
                            Country
                            State (if applicable)
                            Birthdate
                        -->
                        <button type="submit" class="btn btn-info m-4">Change Info</button>
                    </form>
                </div>
            </div>
        </div>

    </div>
    
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en',
                autoDisplay: false
            }, 'google_translate_element'); //remove the layout
        }
    </script>
    <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript">
    </script>
    
    
    <script type="text/javascript">
        function triggerHtmlEvent(element, eventName) {
            var event;
            if (document.createEvent) {
                event = document.createEvent('HTMLEvents');
                event.initEvent(eventName, true, true);
                element.dispatchEvent(event);
            } else {
                event = document.createEventObject();
                event.eventType = eventName;
                element.fireEvent('on' + event.eventType, event);
            }
        }
        
        $('.translation-links a').click(function (e) {
            e.preventDefault();
            var lang = $(this).data('lang');
            $('#google_translate_element select option').each(function () {
                if ($(this).text().indexOf(lang) > -1) {
                    $(this).parent().val($(this).val());
                    var container = document.getElementById('google_translate_element');
                    var select = container.getElementsByTagName('select')[0];
                    triggerHtmlEvent(select, 'change');
                }
            });
        });
    </script>

    <script>
        $(document).ready(function(){
            $('[data-bs-toggle="popover"]').popover();
        });
    </script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
<div class="position-fixed top-0 end-0" style="z-index: 10000">
    <div id="ClipboardAlert" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <strong class="me-auto">Copied to clipboard</strong>
            <small>Now</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
            The username has been copied to your clipboard.
        </div>
    </div>
</div>
</html>

<!-- Modal -->
<div class="modal fade" id="BuyUsername" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">BUY NEW USERNAME</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'atm_functions:Profile' %}?action=BuyUsername" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    <p>Buying and modifying personalized username has a cost of:</p>
                    <p class="text-info" style="text-align: center;">
                        <b>
                            10 CryptoshareCredits
                        </b>
                    </p>
                        <div class="mb-3">
                            <p style="text-align: center;">Please enter your new username</p>
                            <input type="text" class="form-control text-center" id="newUsername" name="newUsername"
                                placeholder="Your new username" maxlength="30">
                        </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success" id="NeverShowAgain">
                        Change Username
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/buy_credit.html
{% load static %}
{% static "images" as baseUrl %}

<!doctype html>
<html lang="en">
{% include 'header.html' %}
<body>
    {% include 'atm_sidebar.html' %}

    <div class="container-fluid">
        {% include 'messages.html' %}
        <h2 class="ml-4">Build Credit</h2>
        
        <br>

        <h1 class="ml-4">COMING SOON</h1>
    </div>

    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en',
                autoDisplay: false
            }, 'google_translate_element'); //remove the layout
        }
    </script>
    <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript">
    </script>
    
    
    <script type="text/javascript">
        function triggerHtmlEvent(element, eventName) {
            var event;
            if (document.createEvent) {
                event = document.createEvent('HTMLEvents');
                event.initEvent(eventName, true, true);
                element.dispatchEvent(event);
            } else {
                event = document.createEventObject();
                event.eventType = eventName;
                element.fireEvent('on' + event.eventType, event);
            }
        }
        
        $('.translation-links a').click(function (e) {
            e.preventDefault();
            var lang = $(this).data('lang');
            $('#google_translate_element select option').each(function () {
                if ($(this).text().indexOf(lang) > -1) {
                    $(this).parent().val($(this).val());
                    var container = document.getElementById('google_translate_element');
                    var select = container.getElementsByTagName('select')[0];
                    triggerHtmlEvent(select, 'change');
                }
            });
        });
    </script>
    
</body>
{% include 'atm_footer.html' %}
</html>

<!-- Modal -->
<div id="CreditGradesModal" class="modal" style="z-index: 2000;">
    <!-- Modal content -->
    <div class="modal-content">
        <div class="modal-header">
            <h3>Get Money to Lend Credit Grade (Equivalent to $USDC)</h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col" style="text-align: center; white-space: nowrap;">CREDIT GRADE</th>
                    <th scope="col" style="text-align: center;">PRICE</th>
                    <th scope="col" style="text-align: center;">ALLOWED BORROWERS (PER MONTH)</th>
                    <th scope="col" style="text-align: center;">TOTAL REVENUE (PER MONTH)</th>
                  </tr>
                </thead>
                <tbody>
                    
                    <tr>
                        <td style="text-align: center;">FFF</td>
                        <td style="text-align: center;">X</td>
                        <td style="text-align: center;">X</td>
                        <td style="text-align: center;">X</td>
                    </tr>
                    
                    <tr>
                        <td style="text-align: center;">FF</td>
                        <td style="text-align: center;">X</td>
                        <td style="text-align: center;">X</td>
                        <td style="text-align: center;">X</td>
                    </tr>

                    <tr>
                        <td style="text-align: center;">F</td>
                        <td style="text-align: center;">$100</td>
                        <td style="text-align: center;">2</td>
                        <td style="text-align: center;">$200</td>
                    </tr>
    
                    <tr>
                        <td style="text-align: center;">E</td>
                        <td style="text-align: center;">$150</td>
                        <td style="text-align: center;">6</td>
                        <td style="text-align: center;">$900</td>
                    </tr>
    
                    <tr>
                        <td style="text-align: center;">D</td>
                        <td style="text-align: center;">$1,000</td>
                        <td style="text-align: center;">(Unlimited)</td>
                        <td style="text-align: center;">(Unlimited)</td>
                    </tr>
    
                    <tr>
                        <td style="text-align: center;">C</td>
                        <td style="text-align: center;">$3000</td>
                        <td style="text-align: center;">(Unlimited)</td>
                        <td style="text-align: center;">(Unlimited)</td>
                    </tr>
    
                    <tr>
                        <td style="text-align: center;">B</td>
                        <td style="text-align: center;">$6,000</td>
                        <td style="text-align: center;">(Unlimited)</td>
                        <td style="text-align: center;">(Unlimited)</td>
                    </tr>
    
                    <tr>
                        <td style="text-align: center;">A</td>
                        <td style="text-align: center;">$9,000</td>
                        <td style="text-align: center;">(Unlimited)</td>
                        <td style="text-align: center;">(Unlimited)</td>
                    </tr>
    
                    <tr>
                        <td style="text-align: center;">AA</td>
                        <td style="text-align: center;">$50,000</td>
                        <td style="text-align: center;">(Unlimited)</td>
                        <td style="text-align: center;">(Unlimited)</td>
                    </tr>
    
                    <tr>
                        <td style="text-align: center;">AAA</td>
                        <td style="text-align: center;">$100,000</td>
                        <td style="text-align: center;">(Unlimited)</td>
                        <td style="text-align: center;">(Unlimited)</td>
                    </tr>
    
                </tbody>
            </table>
        </div>
    </div>
    
</div>

<script>
    window.onload = function() {
        if ({{ request.user.is_authenticated|yesno:"true,false" }}){
            GetCreditGrade();
            GetNotifications();
            if ({{ has_pin|yesno:"false,true" }}){
                $('#CryptoCard').modal('toggle');
            }
        }
    }
</script>
<!-- onclick="$('#BuyUsername').modal('toggle');" -->
<!-- Modal -->
<div class="modal fade" id="CryptoCard" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">THIS SCREEN IS REQUIRED</h5>
            </div>
            <form action="{% url 'atm_functions:BuildCredit' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    {% include 'messages.html' %}

                    <b><h3 style="text-align: center;">CryptosharePay Card Registration & Get 100 CryptoshareCredits</h3></b>
                    <p>CryptosharePay is a "Digital Decentralized Credit Card" that allows you to pay InPerson or Online with a Username and 12 Digit Pin Code.</p>
                    
                    <input type="hidden" name="spc" value="{{ new_pin_start }}">
                    <div class="mb-3">
                        <p style="text-align: center;">Your username</p>
                        <input type="text" class="form-control text-center" id="username" name="username"
                            placeholder="Your new pin" maxlength="6" value="{{ username }}" readonly>
                    </div>
                    <div class="mb-3">
                        <p style="text-align: center;">Generated pin</p>
                        <input type="text" class="form-control text-center" id="startPin" name="startPin"
                            placeholder="Your new pin" maxlength="6" value="{{ new_pin_start }}" readonly>
                    </div>
                    <div class="mb-3">
                        <p style="text-align: center;">Please enter your next 6 digits of your new pin</p>
                        <input type="text" class="form-control text-center" id="newPin" name="newPin"
                            placeholder="Your new pin" maxlength="6" required>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="cb_name_change" name="cb_name_change" required>
                        <label class="form-check-label" for="cb_name_change">
                            I acknowledge by clicking this Checkbox, I have put my 12 Digit Pin in a safe place and "Cryptoshare" is not Responsible for Recovery of my 12 Digit Pin. Username and 12 digit code can be used as a payment method anywhere "CryptoSharePay" Logo is seen.
                        </label>
                    </div>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="submit" class="btn btn-success" id="NeverShowAgain">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/footer.html
{% load static %}
{% static "images" as baseUrl %}
{% include 'crisp_client.html' %}
<footer>
    <script src="https://widgets.coingecko.com/coingecko-coin-price-marquee-widget.js"></script>
    <coingecko-coin-price-marquee-widget  coin-ids="bitcoin,ethereum,litecoin,bitcoin-cash,ripple,stellar,algorand,tezos,cosmos"
    currency="usd" background-color="#ffffff" locale="en">
</coingecko-coin-price-marquee-widget>
</footer>

templates/give_back.html
{% load static %}
{% static "images" as baseUrl %}

<!doctype html>
<html lang="en">
{% include 'header.html' %}
<body>
    {% include 'banner.html' %}
    {% if name is not None %}
    {% include 'a_sessiontimeout.html' %}
    {% endif %}
    <div class="container my-4">
        <div class="row">
            <h3 class="text-primary" style="margin:auto;padding-bottom: 15px;">Greetings, CryptoSharers!</h3>
            <p style="color:black;">Our initiative is to help People of Color have access to cryptocurrency
                and fund projects for Hispanics, Black, and Brown people around the world.
            </p>
        </div>
        <br>
        <h2 class="text-primary" style="margin:auto;text-align: center;">Ways to Give Back</h2>
        <br>
        <p style="color:black;">Coinbase Wallet users can donate cryptocurrency directly to our username, @cryptoshare.</p>
        <p style="color:black;">We also accept donations to the following networks/addresses:</p>
        <ul>
            <li>Etheruem (ETH), ERC-20 tokens (DAI, USDC, LINK, etc.): 0x895489603d8E45C97EF5bd7FDD2D5674A8425835</li>
            <li>Bitcoin Cash (BCH): qqwwanl6wwr2m25d43h42u6vsvtypy3wzs92cgvd8m</li>
            <!-- <li>Bitcoin Cash (BCH) (legacy): 13dz1MEEx8rwGFNtEowXGXKBP5ehXkqMTE  &nbsp; <i>(please do not send Bitcoin (BTC) to this address)</i></li> -->
            <li>XRP: rscbBFJ4y1eWDk4usSzqYTnnpwd86i8dDH</li>
        </ul>
        <br>
        <table width="100%">
            <tr>
                <td width="33%"><img src="{% static '/images/donation/ERC20_QR.png' %}" class="qr"></td>
                <td width="33%"><img src="{% static '/images/donation/BCH_QR.png' %}" class="qr"></td>
                <td width="33%"><img src="{% static '/images/donation/XRP_QR.png' %}" class="qr"></td>
            </tr>
        </table>
        <br><br>
        <a href="{% url 'authentication:Home' %}"><button type="button" class="btn btn-primary">Back</button>
        </a>
    </div>
    <br>
    {% include 'info_card.html' %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% include 'footer.html' %}
    
</body>
</html>

templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class=" alert alert-sm alert-{{ message.tags }}" {% endif %}>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}