ATM/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls.conf import include

urlpatterns = [
    path('', include('authentication.urls', namespace='authentication')),
    path('atm/', include('atm_functions.urls', namespace='atm_functions')),
    path('businesses/', include('businesses.urls', namespace='businesses')),
    path('webhooks/', include('webhooks.urls', namespace='webhooks')),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('cryptosharepay/', include('cryptosharepay.urls', namespace='cryptosharepay')),
    # path('admin/', admin.site.urls),
]

atm_functions/urls.py
from django.urls import path
from . import views

app_name = "atm_functions"
urlpatterns = [
     path("", views.home, name="Home"),
     path("ApproveWallet/", views.approve_wallet, name="ApproveWallet"),

     path("Contacts/", views.contacts, name="Contacts"),
     path("Contacts/Create", views.create_contact, name="CreateContact"),
     path("Contacts/Delete", views.delete_contact, name="DeleteContact"),

     path("Referrals/", views.referrals, name="Referrals"),
     path("ReferralsAdmin/", views.referrals_admin, name="ReferralsAdmin"),

     # path("EstateNetWorth/", views.estate_net_worth, name="EstateNetWorth"),
     # path("EditEstateNetWorth/", views.edit_estate_net_worth, name="EditEstateNetWorth"),

     # path("BlockchainWills/", views.blockchain_wills, name="BlockchainWills"),
     # path("RegisterBlockchainWill/", views.register_blockchain_will, name="RegisterBlockchainWill"),
     # path("CertificateBlockchainWill/", views.certificate_blockchain_will, name="CertificateBlockchainWill"),     
     # path("CertificateBlockchainWill/<int:id>/", views.certificate_blockchain_will, name="CertificateBlockchainWill"),    

     path("BuyCrypto/", views.buy_crypto, name="BuyCrypto"),
     path("BuildCredit/", views.buy_credit, name="BuildCredit"),
     path("BuyCryptoWidget/", views.buy_crypto_widget, name="BuyCryptoWidget"),

     path("BuildCreditCrypto/<str:code>/", views.buy_credit_with_crypto, name="BuildCreditCrypto"),

     path("CheckCredit/", views.check_balance, name="CheckCredit"),
     path("CreditGrades/", views.credit_grades, name="CreditGrades"),
     path("CryptoShareWallet/", views.cryptoshare_wallet, name="CryptoShareWallet"),

     path("CreditRatings/", views.credit_rankings, name="CreditRatings"),

     path("StripeCheckout/", views.stripe_checkout, name="StripeCheckout"),
     path("StripeCheckoutResult/", views.stripe_checkout_result, name="StripeCheckoutResult"),

     path("CryptoNews/", views.crypto_news, name="CryptoNews"),

     path("ConnectWallet/", views.connect_wallet, name="ConnectWallet"),
     path("DisconnectWallet/", views.disconnect_wallet, name="DisconnectWallet"),
     path("GenerateAddress/", views.generate_address, name="GenerateAddress"),

     path("Insurance/", views.insurance, name="Insurance"),
     path("BuySecurity/", views.buy_security, name="BuySecurity"),
     path("BuyProtection/<str:selected_plan>/", views.buy_protection_plan, name="BuyProtectionPlan"),

     path("MyAddresses/", views.my_addresses, name="MyAddresses"),
     path("MyTransactions/", views.my_transactions, name="MyTransactions"),

     path("Profile/", views.profile, name="Profile"),
     path("SwapCrypto/", views.swap_crypto, name="SwapCrypto"),
     path("Settings/", views.atm_settings, name="Settings"),
     
     path("SendCoinbaseWallet/", views.send_coinbase_wallet, name="SendCoinbaseWallet"),
     path("SendCryptoShareWallet/", views.send_cryptoshare_wallet, name="SendCryptoShareWallet"),

     path("SendCryptoShareCredits/", views.send_cryptoshare_credits, name="SendCryptoShareCredits"),
     path("RequestCryptoShareCredits/", views.request_cryptoshare_credits, name="RequestCryptoShareCredits"),

     path("SendMoneyConfirmation/", views.send_money_confirmation, name="SendMoneyConfirmation"),
     path("TransferMoney/", views.transfer_money, name="TransferMoney"),
     path("TransferCredits/", views.transfer_credits, name="TransferCredits"),

     #API ENDPOINTS
     path("SimpleSwapAPI/", views.simpleswap_api, name="SimpleSwapAPI"),
     path("GetCreditGrade/", views.get_credit_grade, name="GetCreditGrade"),
     path("GetAccountData/", views.get_account_data, name="GetAccountData"),
     path("CurrenciesWidget/", views.get_currencies_balance_widget, name="CurrenciesWidget"),


     #WEBHOOKS
     path("ConfirmationsCoinTransactions/", views.confirmations_coin_transactions, name="ConfirmationsCryptoTransactions"),
     path("ConfirmedCoinTransactions/", views.confirmed_coin_transactions, name="ConfirmedCoinTransactions"),
     path("ConfirmedTokenTransactions/", views.confirmed_token_transactions, name="ConfirmedTokenTransactions"),

     path("StripeWebhook/", views.stripe_webhook, name="StripeWebhook"),

     path("DailyRoutine/", views.daily_routine, name="DailyRoutine"),

     path("UpdateExchangeRates/", views.update_exchange_rates, name="UpdateExchangeRates"),

     path("RegisterWaitlistEmail/", views.register_waitlist_email, name="RegisterWaitlistEmail"),
     
     path("TestReceiver/", views.test_receiver, name="TestReceiver"),
     # path("TestClient/", views.test_client, name="TestClient")
     # path("NotificationService/", views.notification_service, name="NotificationService")
]

authentication/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from . import views

app_name = 'authentication'
urlpatterns = [
    path('', views.home, name='Home'),
    path('Email/', views.email, name='Email'),
    path('GiveBack/', views.give_back, name="GiveBack"),
    path('Verify/', views.verify, name='Verify'),
    path('Signing/', views.signing, name='Signing'),
    path('Registration/', views.registration, name='Registration'),
    path('PasswordReset', views.reset_password, name="PasswordReset"),
    path('Login/', views.views.login, name='Login'),
    path('Logout/', views.logout, name='Logout')
]

businesses/urls.py
from django.urls import path
from . import views

app_name = "businesses"

urlpatterns = [
    path("", views.businesses, name="Businesses"),
    path("create/", views.create_business, name="Create"),
    path("manage/", views.manage_businesses, name="Manage"),
    path("manage/<int:id_business>/", views.manage_business, name="ManageBusiness"),
    path("edit/", views.edit_business, name="Edit"),
    path("search/", views.search_business, name="Search"),

    path("manage/<int:id_business>/sales/", views.manage_sales, name="ManageSales"),
    path("manage/<int:id_business>/sales/messages/<int:id_purchase>", views.sale_messages, name="SaleMessages"),
    path("manage/<int:id_business>/sales/messages/<int:id_purchase>/send", views.sale_send_message, name="SaleSendMessage"),

    path("create/product/<int:id_business>/", views.create_product, name="CreateProduct"),
    path("delete/product/<int:id_business>/<int:id_product>/", views.delete_product, name="DeleteProduct"),
    path("manage/product/<int:id_business>/", views.manage_products, name="ManageProduct"),

]

businesses/views.py
from django.conf import settings as django_settings
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.http import Http404

from common.emails import sale_business_send_message

from .models import Business, BusinessMessages
from atm_functions.models import Balance, DigitalCurrency, DynamicUsername
from marketplace.models import Product, DigitalService, PurchaseHistory

from decimal import Decimal

# Create your views here.


@login_required()
def businesses(request):
    businesses = Business.objects.all()

    context = {
            'businesses': businesses
            }
            
    return render(request, 'businesses/businesses.html', context)

@login_required()
def manage_sales(request, id_business):

    context = {}

    business = Business.objects.get(
        id_business = id_business
        )

    business_sales = PurchaseHistory.objects.filter(
        product__business = business
        )

    context["business"] = business
    context["business_sales"] = business_sales

    return render(request, 'businesses/sales/manage_sales.html', context)

    pass

@login_required()
def create_business(request):

    if request.method == "GET":
        return render(request, 'businesses/create_business.html')

    if request.method == "POST":
        business_official_name = request.POST.get("business_name", None)
        business_username = request.POST.get("business_username", None).lower().replace(" ", "")
        business_system_name = business_official_name.lower()
        business_category = request.POST.get("business_category", None)
        business_price = 50      #PRICE IN CRYPTOSHARECREDITS

        business_username = business_username.replace(" ", "")

        if DynamicUsername.objects.filter(id_username=business_username).exists():
            messages.warning(request, "Username already exists.")

            return redirect('businesses:Create')

        name_exists = Business.objects.filter(system_name=business_system_name)
        if name_exists:
            messages.info(request, "Business name already exists.")
            return redirect('businesses:Create')

        digital_currency_object = DigitalCurrency.objects.get(symbol="CSC")
        user_balance = Balance.objects.get(email = request.user, digital_currency_name = digital_currency_object)

        if user_balance.amount < business_price:
            messages.info(request, "You do not have enough funds to create a business. Please buy more CryptoshareCredits.")
            return redirect('atm_functions:Home')
        
        user_balance.amount -= Decimal(business_price)
        user_balance.save()

        new_business = Business(owner=request.user, official_name=business_official_name, system_name=business_system_name, category=business_category)
        new_business.save()

        new_username = DynamicUsername.objects.create(
            id_username = business_username,
            username_type = "BUSINESS",
            business_reference = new_business
        )

        messages.info(request, "Business created successfully.")
        return redirect('businesses:Businesses')

@login_required()
def edit_business(request):

    business_id = request.GET.get("id", None)

    if not business_id:
        return redirect('businesses:Manage')

    if not Business.objects.filter(id_business=business_id).exists():
        return redirect('businesses:Manage')

    business = Business.objects.get(id_business=business_id)

    if request.method == "GET":

        if business.system_name:
            business.system_name = business.system_name.replace(" ", "-")

        context = {
            'business': business
        }

        return render(request, 'businesses/edit_businesses.html', context)
    
    if request.method == "POST":
        
        business_id = int(request.POST.get("business_id", None))
        business_category = request.POST.get("business_category", None)
        business_logo_url = request.POST.get("business_logo", None)

        if len(business_logo_url) > 255:
            messages.info(request, "Image name is too long, please rename it and try again.")
            return redirect('businesses:Edit')

        business = Business.objects.get(id_business=business_id)
        business.category = business_category
        business.logo_url = business_logo_url
        business.save()

        messages.info(request, "Business updated successfully.")
        return redirect('businesses:Manage')

    return render(request, 'businesses/edit_businesses.html')


@login_required()
def manage_businesses(request):
    businesses = Business.objects.filter(owner=request.user)

    context = {
        "businesses": businesses
    }

    return render(request, 'businesses/manage_businesses.html', context)

@login_required()
def manage_business(request, id_business = None):

    if not Business.objects.filter(id_business = id_business, owner = request.user).exists():
        raise Http404()

    context = {}

    business = Business.objects.get(id_business = id_business)

    context["business"] = business

    return render(request, 'businesses/manage_business.html', context)

@login_required()
def search_business(request):

    if request.method == "GET":
        businesses = Business.objects.all()

    if request.method == "POST":                
        search_option = request.POST.get("SearchOption", None)
        search_value = request.POST.get("SearchValue", None)

        if search_option == "StartsWith":
            businesses = Business.objects.filter(system_name__startswith=search_value.lower())

        elif search_option == "Contains":
            businesses = Business.objects.filter(system_name__contains=search_value.lower())

        elif search_option == "ExactMatch":
            businesses = Business.objects.filter(system_name=search_value.lower())

    context = {
        "businesses": businesses
    }

    return render(request, 'businesses/search_businesses.html', context)


@login_required()
def create_product(request, id_business = None):

    if not Business.objects.filter(id_business = id_business, owner = request.user).exists():
        raise Http404()

    context = {}

    business = Business.objects.get(id_business = id_business)

    if request.method == "GET":

        context["business"] = business

        return render(request, 'businesses/products/create_product.html', context)

    elif request.method == "POST":                  
        product_name = request.POST.get("product_name", None)
        product_photo_url = request.POST.get("product_photo", None)
        product_price = request.POST.get("product_price", None)
        product_description = request.POST.get("product_description", None)
        product_extra = request.POST.get("product_extra", None)

        if business.system_category == "DIGITAL_SERVICES":

            product_video_url = request.POST.get("product_video", None)
            product_calendar_url = request.POST.get("product_calendar", None)

            new_digital_service = DigitalService.objects.create(
                name = product_name,
                price = product_price,
                photo_url = product_photo_url,
                description = product_description,
                video_url = product_video_url,
                calendar_url = product_calendar_url,
                extra_url = product_extra
            )

            new_product = Product.objects.create(
                business = business,
                category = business.system_category,
                digital_service_reference = new_digital_service
            )
        
        messages.success(request, "Product created successfully.")

        return redirect('businesses:ManageBusiness', id_business=business.id_business)

@login_required()
def delete_product(request, id_business = None, id_product = None):
    if not Product.objects.filter(id_product = id_product, business__owner = request.user).exists():
        messages.error(request, "You can't do that!", extra_tags='danger')

        return redirect('businesses:ManageProduct')


    product = Product.objects.get(id_product = id_product, business__owner = request.user)

    if product.category == "DIGITAL_SERVICES":
        inner_product = product.digital_service_reference

    product.delete()

    messages.success(request, "Product deleted successfully.")

    return redirect('businesses:ManageProduct', id_business=id_business)

@login_required()
def manage_products(request, id_business = None):
    if not Business.objects.filter(id_business = id_business, owner = request.user).exists():
        raise Http404()

    context = {}

    business = Business.objects.get(id_business = id_business)

    if request.method == "GET":

        products = Product.objects.filter(business = business)

    context["business"] = business
    context["products"] = products

    return render(request, 'businesses/products/manage_products.html', context)

@login_required()
def sale_messages(request, id_business = None, id_purchase = None):
    if not Business.objects.filter(id_business = id_business, owner = request.user).exists() or not PurchaseHistory.objects.filter(id_purchase = id_purchase, product__business__id_business = id_business).exists():
        raise Http404()

    context = {}

    business = Business.objects.get(id_business = id_business)

    business_messages = BusinessMessages.objects.filter(
        id_purchase = id_purchase
    )

    context["business"] = business
    context["id_purchase"] = id_purchase
    context["business_messages"] = business_messages

    return render(request, 'businesses/sales/sale_messages.html', context)

def sale_send_message(request, id_business = None, id_purchase = None):
    print("TEST")

templates/businesses/businesses_sidebar.html
{% load static %}
{% static "images" as baseUrl %}
{% if request.user.is_authenticated %}
{% include 'a_sessiontimeout.html' %}
{% include 'includes/notifications_sidebar.html' %}
{% endif %}

{% include 'includes/notifications_sidebar.html' %}
        <!--========== BOX ICONS ==========-->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <!--========== HEADER ==========-->
    <header class="header">
        <div class="header__container">
            <img src="{% static '/images/logo.png' %}" alt="" class="header__img" onclick='location.href="{% url 'atm_functions:Home' %}"'>

            {% if request.user.is_authenticated %}

            {% include 'currencies_widget.html' %}
            {% endif %}


            <div class="header__toggle">
                <i class='bx bx-menu' id="header-toggle" style="color: white;"></i>
            </div>
        </div>
    </header>


<br>
<div class="nav" id="navbar">
    <nav class="nav__container">
        <div>           
            <div class="nav__items nav__logo">
                <!-- <a href="{% url 'atm_functions:Home' %}" class="sidebar-logo"><img src="{% static '/images/logo.png' %}"></a> -->

                {% if request.user.is_authenticated %}
    
                <span class="nav__logo-name mt-2" id="credit_grade" style="color: white;"><b>CREDIT GRADE: </b></span>
    
                <span class="nav__name" ><a href="{% url 'atm_functions:BuildCredit' %}">(Improve Credit Grade)</a></span>

                <a class="btn btn-primary nav__name" data-bs-toggle="offcanvas" href="#offcanvasRight" role="button" aria-controls="offcanvasRight">
                    <i class='bx bxs-bell' style="color: gold;"></i>
                </a>
                {% endif %}

            </div>

            <div class="nav__list">
                <div class="nav__items">
                    <a href="{% url 'atm_functions:Home' %}" class="nav__link">
                        <i class='nav__icon bx bx-arrow-back' style="color: gold;"></i>
                        <span class="nav__name">GO BACK</span>
                    </a>
                </div>
                <div class="nav__items">
                    <h3 class="nav__subtitle">BUSINESSES</h3>

                    <a href="{% url 'businesses:Businesses' %}" class="nav__link">
                        <i class="nav__icon bx bxs-home" style="color: gold;"></i>
                        <span class="nav__name">HOME</span>
                    </a>

                    <a href="{% url 'businesses:Create' %}" class="nav__link">
                        <i class="nav__icon bx bxs-folder-plus" style="color: gold;"></i>
                        <span class="nav__name">CREATE BUSINESS</span>
                    </a>

                    <a href="{% url 'businesses:Manage' %}" class="nav__link">
                        <i class="nav__icon bx bxs-chart" style="color: gold;"></i>
                        <span class="nav__name">MANAGE BUSINESS</span>
                    </a>

                    <a href="{% url 'businesses:Search' %}" class="nav__link">
                        <i class="nav__icon bx bx-search-alt" style="color: gold;"></i>
                        <span class="nav__name">SEARCH BUSINESS</span>
                    </a>
                </div>
            </div>
        </div>

        {% if request.user.is_authenticated %}
        <form action="{% url 'authentication:Logout' %}" id="logout" method="POST">
            {% csrf_token %}
        </form>
        <a onclick="$('#logout').submit();" href="#logout" class="nav__link nav__logout">
            <i class='bx bx-log-out nav__icon' ></i>
                <span class="nav__name">Log Out</span>
        </a>
        
        {% endif %}
    </nav>
</div>
{% include 'crisp_client.html' %}

    
<script type="text/javascript">
    window.onload = function() {
        // console.log(localStorage.hideAlert);
        // if (!localStorage.hideAlert) {
        //     $('#DepositWarning').modal('toggle');
        // }
        if ({{ request.user.is_authenticated|yesno:"true,false" }}){
            GetCreditGrade();
            GetNotifications();
        }
    }

    function neverShowAgainModal() {
        localStorage.setItem('hideAlert', true);
        $("#DepositWarning").modal('hide');
    };

    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != "") {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
                }
            }
        }
        return cookieValue;
    }
    // document.getElementById("pay_amount").innerHTML = "Amount : "+ offerAmount;

    function GetCreditGrade(){
        var url = "{% url 'atm_functions:GetCreditGrade' %}";
        var data = {
            csrfmiddlewaretoken: getCookie('csrftoken')
        };
        $.ajax({
            type: "POST",
            url: url,
            data: data,
            success: function(response){
                document.getElementById("credit_grade").innerHTML = "CREDIT GRADE: "+ response["credit_grade"];
            },
            error: function(response){
                document.getElementById("credit_grade").innerHTML = "CREDIT GRADE: ERROR";
            }
        });
    };
</script>
<script src="{% static 'js/sidebar.js' %}"></script>


<style>
    .sidebarCoin {
        height: 20px;
        width: auto;
        position: relative;
        padding-left: 5px;
    }
</style>

templates/businesses/manage_business.html
{% load static %}
{% load tz %}
{% static "images" as baseUrl %}

<!doctype html>
<html lang="en">
{% include 'header.html' %}
<body>
    {% include 'businesses/businesses_sidebar.html' %}

    <div class="content-container">
        {% include 'messages.html' %}

        <h2 class="text-primary text-center">{{ business.official_name }}</h2>
        <br>

        <div class="container mb-4">
            <div class="row gy-5">
                <div class="d-grid gap-2 col-6 mx-auto">
                    <a class="btn btn-primary" href="{% url 'businesses:Edit' %}?id={{ business.id_business }}" role="button">
                        Edit Business
                    </a>
                    <a class="btn btn-primary" href="{% url 'businesses:ManageSales' id_business=business.id_business %}" role="button">
                        Business Sales
                    </a>
                    <!-- <button class="btn btn-primary" type="button">2</button> -->
                </div>
                <div class="d-grid gap-2 col-6 mx-auto">
                    <a class="btn btn-primary {% if business.system_category != "DIGITAL_SERVICES" %} disabled {% endif %}" href="{% url 'businesses:CreateProduct' id_business=business.id_business %}" role="button">
                        Add Product / Service
                    </a>
                    <a class="btn btn-primary" href="{% url 'businesses:ManageProduct' id_business=business.id_business %}" role="button">
                        Business Products / Services
                    </a>
                    <!-- <button class="btn btn-primary" type="button">4</button> -->
                </div>
            </div>
        </div>

        <div class="container">
            <div class="card col-md-12 border border-info bg-light text-center" style="border-radius: 5%;">
                <img src="{{ business.logo_url }}"
                    class="d-block mx-auto" style="width: auto; height: 300px;" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ business.official_name }}
                    </h5>
                    <h6 class="card-subtitle mb-2 text-muted">
                        <u>
                            {{ business.creation_datetime }}
                        </u>
                    </h6>
                    
    
                    <p class="card-text">
                        <b>OWNER:</b> {{ business.owner.get_full_name }}
                    </p>

                    <p class="card-text">
                        <b>CATEGORY:</b> {{ business.category }}
                    </p>
                </div>
            </div>
        </div>        
    </div>
    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en',
                autoDisplay: false
            }, 'google_translate_element'); //remove the layout
        }
    </script>
    <script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript">
    </script>
    
    
    <script type="text/javascript">
        function triggerHtmlEvent(element, eventName) {
            var event;
            if (document.createEvent) {
                event = document.createEvent('HTMLEvents');
                event.initEvent(eventName, true, true);
                element.dispatchEvent(event);
            } else {
                event = document.createEventObject();
                event.eventType = eventName;
                element.fireEvent('on' + event.eventType, event);
            }
        }
        
        $('.translation-links a').click(function (e) {
            e.preventDefault();
            var lang = $(this).data('lang');
            $('#google_translate_element select option').each(function () {
                if ($(this).text().indexOf(lang) > -1) {
                    $(this).parent().val($(this).val());
                    var container = document.getElementById('google_translate_element');
                    var select = container.getElementsByTagName('select')[0];
                    triggerHtmlEvent(select, 'change');
                }
            });
        });
    </script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>